# Generated by Django 4.0.2 on 2022-02-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location_id',
        ),
        migrations.AddField(
            model_name='user',
            name='location_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
